spring.application.name=innohack-backend

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/inno_hack
spring.datasource.username=postgres
spring.datasource.password=nithya@0604
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=8080
